### ISSUE TITLE
Differences between 2.0.0 and newer

### ISSUE THREAD

**Issue by danbigthink** [CardanoSharp/cardanosharp-wallet#75]
Hi,

I've been using this library for a while now and recall coming across an issue when submitting a transaction I get an error:
TextEnvelope decode error: DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 1 "Size mismatch when decoding \nRecord RecD.\nExpected 4, but found 3.").

My unity game is using version 2.0.0 and works fine, I never see this error. I forgot I downgraded it to 2.0.0 rather than a newer version due to some bug around sending tokens.
Recently I created an api that uses 2.6.0 of this library and this error came back again. Downgrading my dependency on this library to 2.0.0 from 2.6.0 in nuget and everything works fine.

Any idea why this would happen?
I reviewed the signed transactions manually and found they were like 1 byte different

**Comment by safestak-keith** [comment]
Hi @danbigthink - there had been quite a few changes since 2.0.0 including adding an field added to the Tx CBOR but it will be hard to debug without knowing more about your specific transaction. Are you on the[ CardanoSharp discord](https://discord.gg/fT777VUA)? Please [ask the question there](https://discord.gg/fT777VUA)

**Comment by danbigthink** [comment]
Thanks @safestak-keith
