### ISSUE TITLE
Plutus Script Support

### ISSUE THREAD

**Issue by nothingalike** [CardanoSharp/cardanosharp-wallet#99]
Update the library to support Plutus Script V2.

## Bounty 1500 ADA

**Comment by MarianSWA** [comment]
I'll also add $1000 to the bounty for this feature 🔥

**Comment by nothingalike** [comment]
this will be helpful: https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl

**Comment by MarianSWA** [comment]
Hi, any news on this? Eagerly waiting got it 😃

**Comment by MarianSWA** [comment]
@NicholasMaselli @nothingalike sorry to ask again, but any information would be great. We've made promises further based on the initial estimations for the plutus scripts, and we are in the position to delay again, but we need to know at least a rough estimate. Thank you

**Comment by Shade-of-Sorcery** [comment]
I'm not on the dev team but I can see the work that has been done on this is in the pull requests. You might check out this repo to see the current state of things:

https://github.com/Orion-Crypto/cardanosharp-wallet

**Comment by nothingalike** [comment]
@MarianSWA nick said he will be adding unit tests next for the merge

@Shade-of-Sorcery that repo is from @NicholasMaselli and is what will be merged into this repo

**Comment by MarianSWA** [comment]
Hi @nothingalike @NicholasMaselli the implementation seems so close to completion, any estimation about the final merge? Is it close?
We're running out of funds and we need to know if we should wait for this or use the money we initially added to the bounty for something else. It's been 6 months since then and didn't anticipate it would take this long, so we can't keep that amount blocked for that long.
What do you think? If the implementation is really close to finish and could be completed until the end of the month we will keep the money reserved until then. If not, we'll unfortunately have to withdraw it, but it would be really useful to know if it's impossible to merge until then, as soon as possible. Thank you, guys!

**Comment by nothingalike** [comment]
I believe were going to start the process of merging nicks work this weekend. Sorry this is taking so long

**Comment by MarianSWA** [comment]
@nothingalike Cool, this would be great!

**Comment by MarianSWA** [comment]
Nice! I now realized that the merge was already done and it's up and running on nuget too. 
@NicholasMaselli if you have a Binance ID / Pay ID could you share it? Or another way of receiving busd. I'll be moving the money in the following days, and send it to you.
@nothingalike Is there a short doc for the new feature yet? I'll be testing in the following days and it would help a lot
Thanks to both of you!

**Comment by nothingalike** [comment]
> @nothingalike Is there a short doc for the new feature yet? I'll be testing in the following days and it would help a lot Thanks to both of you!

@MarianSWA please see the unit tests for Plutus Script examples. we have 2 tests that show you high level how to leverage plutus scripts. i'm working on adding more tests.
